### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by ShinyPuppy** [m1enkrafftman/AntiCheatPlus#4]
I see the exempt perm is now fixed, thanks for that. But with this new update I'm now experiencing several other issues which are, increase lag and MorePackets check constantly going off and kicking players. The old version, 2.0.8 does not have any of these issues, so not sure whats wrong there.
If you need any other info let me know.

Kind Regards

**Comment by m1enkrafftman** [comment]
Try and figure out the source of the lag. As mentioned in the known caveats, when your server's TPS get very low, many false positives arise. If you can for sure identify AC+ as the source of the lag, reopen this issue and explain it. As for morepackets, I haven't touched that check between 2.0.8 and 2.0.9, so the problem seems to be with your server's performance.
